const year = (new Date()).getFullYear();

export const TEXT = {
  logo: 'Need for drive',
  carsharing: 'Каршеринг',
  needDrive: 'Need for drive',
  offerSubTitle:'Поминутная аренда авто твоего города',
  license: `© 2016-${year} «Need for drive»`,
  telephone:'8 (495) 234-22-44',
  book:'Забронировать',
  details: 'Подробнее',
  choseCity: 'Выберите город',
  choseOnMap: 'Выбрать на карте',
  city: 'Город',
  pickup: 'Пункт выдачи',
  chosePickUp: 'Начните вводить пункт ...',
  totalTitle: 'Ваш заказ',
  order: 'Заказ',
  toOrder: 'Заказать',
  model: 'Модель',
  color: 'Цвет',
  duration: 'Длительность аренды',
  rate: 'Тариф',
  price: 'Цена',
  total: 'Итого',
  choseModel: 'Выбрать модель',
  allModels: 'Все модели',
  additionally: 'Дополнительно',
  from: 'от',
  to: 'до',
  rentDate: 'Дата аренды',
  additionalServices: 'Доп услуги',
  currency: '₽',
  fullTank: 'Полный бак',
  needChildChair: 'Детское кресло',
  rightWheel: 'Правый руль',
  fromTime: 'С',
  toTime: 'По',
  choseDateTime: 'Введите дату и время',
  yes: 'Да',
  d: 'д',
  h: 'ч',
  fuel: 'Топливо',
  availableFrom: 'Доступна с',
  minimalFuel: '"Минимум"',
  confirm: 'Подтвердить',
  return: 'Вернуться',
  confirmOrder: 'Подтвердите заказ',
  cancel: 'Отменить',
  orderNumber: 'Заказ номер',
}