const year = (new Date()).getFullYear();

export const TEXT = {
  logo: 'Need for drive',
  carsharing: 'Каршеринг',
  needDrive: 'Need for drive',
  offerSubTitle:'Поминутная аренда авто твоего города',
  license: `© 2016-${year} «Need for drive»`,
  telephone:'8 (495) 234-22-44',
  book:'Забронировать',
  details: 'Подробнее',
  choseCity: 'Выберите город',
  city: 'Город',
  pickup: 'Пункт выдачи',
  chosePickUp: 'Начните вводить пункт ...',
  totalTitle: 'Ваш заказ',
  model: 'Модель',
  color: 'Цвет',
  duration: 'Длительность аренды',
  rate: 'Тариф',
  price: 'Цена',
  total: 'Итого',
  choseModel: 'Выбрать модель',
  additionally: 'Дополнительно',
  from: 'от',
  to: 'до',
}